sudo: false
language: ruby

rvm:
  - "2.4.1"
  - "2.3.4"
  - "2.2.7"
  - "2.1.10"

env:
  - ACTIVE_RECORD_BRANCH="master"
  - ACTIVE_RECORD_BRANCH="5-1-stable"
  - ACTIVE_RECORD_BRANCH="5-0-stable"
  - ACTIVE_RECORD_BRANCH="4-2-stable"
  - ACTIVE_RECORD_VERSION="~> 5.1.0"
  - ACTIVE_RECORD_VERSION="~> 5.0.0"
  - ACTIVE_RECORD_VERSION="~> 4.2.0"

matrix:
  allow_failures:
    - env: ACTIVE_RECORD_BRANCH="master"
    - env: ACTIVE_RECORD_BRANCH="5-1-stable"
    - env: ACTIVE_RECORD_BRANCH="5-0-stable"
    - env: ACTIVE_RECORD_BRANCH="4-2-stable"
  exclude:
    - rvm: "2.1.10"
      env: ACTIVE_RECORD_BRANCH="master"
    - rvm: "2.1.10"
      env: ACTIVE_RECORD_BRANCH="5-1-stable"
    - rvm: "2.1.10"
      env: ACTIVE_RECORD_BRANCH="5-0-stable"
    - rvm: "2.1.10"
      env: ACTIVE_RECORD_VERSION="~> 5.1.0"
    - rvm: "2.1.10"
      env: ACTIVE_RECORD_VERSION="~> 5.0.0"
